### Подключение к базе и таблицы с юзерами и постами

In [3]:
from sqlalchemy import create_engine

engine = create_engine("postgresql://robot-startml-ro:pheiph0hahj1Vaif@postgres.lab.karpov.courses:6432/startml")
connection = engine.connect().execution_options(stream_results=True)

In [4]:
# Данные по posts
import pandas as pd

posts = pd.read_sql(
    """SELECT * FROM public.post_text_df""",
    con=connection
)

posts

      post_id                                               text     topic
0           1  UK economy facing major risks\n\nThe UK manufa...  business
1           2  Aids and climate top Davos agenda\n\nClimate c...  business
2           3  Asian quake hits European shares\n\nShares in ...  business
3           4  India power shares jump on debut\n\nShares in ...  business
4           5  Lacroix label bought by US firm\n\nLuxury good...  business
...       ...                                                ...       ...
7018     7315  OK, I would not normally watch a Farrelly brot...     movie
7019     7316  I give this movie 2 stars purely because of it...     movie
7020     7317  I cant believe this film was allowed to be mad...     movie
7021     7318  The version I saw of this film was the Blockbu...     movie
7022     7319  Piece of subtle art. Maybe a masterpiece. Doub...     movie

[7023 rows x 3 columns]

In [6]:
# Будем работать с тремя моделями 

from transformers import AutoTokenizer
from transformers import BertModel
from transformers import RobertaModel
from transformers import DistilBertModel


def get_model(model_name):
    assert model_name in ['bert', 'roberta', 'distilbert']

    checkpoint_names = {
        'bert': 'bert-base-cased',
        'roberta': 'roberta-base',
        'distilbert': 'distilbert-base-cased'
    }

    model_classes = {
        'bert': BertModel,
        'roberta': RobertaModel,
        'distilbert': DistilBertModel
    }

    return AutoTokenizer.from_pretrained(checkpoint_names[model_name]), model_classes[model_name].from_pretrained(checkpoint_names[model_name])

# Выбираем модель DistilBERT (оптимизирована по скрости и размеру)
tokenizer, model = get_model('distilbert')

In [8]:
# Создадим датасет для постов

from torch.utils.data import Dataset
from torch.utils.data import DataLoader
from transformers import DataCollatorWithPadding


class PostDataset(Dataset):
    def __init__(self, texts, tokenizer):
        super().__init__()

        self.texts = tokenizer.batch_encode_plus(
            texts,
            add_special_tokens=True,
            return_token_type_ids=False,
            return_tensors='pt',
            truncation=True,
            padding=True
        )
        self.tokenizer = tokenizer

    def __getitem__(self, idx):
        return {'input_ids': self.texts['input_ids'][idx], 'attention_mask': self.texts['attention_mask'][idx]}

    def __len__(self):
        return len(self.texts['input_ids'])
    
# Создаем Dataset, возвращающий токенизированные примеры по индексу    
dataset = PostDataset(posts['text'].values.tolist(), tokenizer)
# Собираем элементы в батч и динамически делаем padding до max длины в батче
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)
# Создаем итератор, выдающий батчи тензоров, готовые к переносу на device
loader = DataLoader(dataset, batch_size=32, collate_fn=data_collator, pin_memory=True, shuffle=False)

In [9]:
# Выбираем GPU (если есть) или CPU, выводим выбранное устройство и имя GPU, затем переносим модель на это устройство.

import torch
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

print(device)
print(torch.cuda.get_device_name())

model = model.to(device)

cuda:0
Tesla T4

In [10]:
# Создаем и вызываем функцию, которая в режиме инференса прогоняет батчи через модель, извлекает CLS‑векторы для каждого примера, 
# аккумулирует их на CPU и возвращает объединённый тензор всех эмбеддингов.

from tqdm import tqdm

@torch.inference_mode()
def get_embeddings_labels(model, loader):
    model.eval()
    
    total_embeddings = []
    
    for batch in tqdm(loader):
        batch = {key: batch[key].to(device) for key in ['attention_mask', 'input_ids']}

        embeddings = model(**batch)['last_hidden_state'][:, 0, :]

        total_embeddings.append(embeddings.cpu())

    return torch.cat(total_embeddings, dim=0)

embeddings = get_embeddings_labels(model, loader).numpy()
embeddings

100%|██████████| 220/220 [01:52<00:00,  1.96it/s]

array([[ 3.6315086e-01,  4.8937496e-02, -2.6408118e-01, ...,
        -1.4159346e-01,  1.5918216e-02,  9.1982896e-05],
       [ 2.3641640e-01, -1.5950108e-01, -3.2779828e-01, ...,
        -2.8993604e-01,  1.1936528e-01, -1.6235473e-03],
       [ 3.7519148e-01, -1.1394388e-01, -2.4054705e-01, ...,
        -3.3891949e-01,  5.8694065e-02, -2.1265799e-02],
       ...,
       [ 3.4038273e-01,  6.6492192e-02, -1.6318429e-01, ...,
        -8.6562753e-02,  2.0340374e-01,  3.2090571e-02],
       [ 4.3209219e-01,  1.1091532e-02, -1.1730607e-01, ...,
         7.5401559e-02,  1.0273975e-01,  1.5274222e-02],
       [ 3.0427766e-01, -7.6215670e-02, -6.7758739e-02, ...,
        -5.4348916e-02,  2.4438348e-01, -1.4148588e-02]], dtype=float32)

In [11]:
# Центрируем эмбеддинги по признакам и проецируем их в пространство из 50 главных компонент методом PCA.

from sklearn.decomposition import PCA

centered = embeddings - embeddings.mean(axis=0)
pca = PCA(n_components=50)
pca_decomp = pca.fit_transform(centered)

In [13]:
# Обучаем KMeans на PCA‑представлении, добавляем метку кластера в posts['TextCluster'] и сохраняем
# расстояния до всех центров как числовые признаки.

from sklearn.cluster import KMeans

n_clusters = 10
kmeans = KMeans(n_clusters=n_clusters, random_state=0).fit(pca_decomp)
posts['TextCluster'] = kmeans.labels_

dists_columns = [f'DistanceToCluster_{i}' for i in range(n_clusters)]

dists_df = pd.DataFrame(
    data=kmeans.transform(pca_decomp),
    columns=dists_columns
)

dists_df.head()

/opt/conda/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

,DistanceToCluster_0,DistanceToCluster_1,DistanceToCluster_2,DistanceToCluster_3,DistanceToCluster_4,DistanceToCluster_5,DistanceToCluster_6,DistanceToCluster_7,DistanceToCluster_8,DistanceToCluster_9
0,3.375463,2.827366,3.286124,3.392758,3.609495,3.388122,2.366426,2.194448,2.990085,1.770638
1,3.329094,2.551211,2.962308,3.332920,3.347059,3.150867,2.333067,2.211535,2.838212,1.707563
2,3.264548,2.863519,3.058967,3.384545,3.348653,3.204419,2.392042,3.004334,3.041477,1.611540
3,3.521580,3.357555,3.793170,3.658642,3.795354,3.722914,2.815526,3.367651,3.250493,2.338428
4,3.049469,2.134254,2.847575,2.814365,3.043573,2.751275,2.034956,2.911702,2.653575,1.706435

In [14]:
posts = pd.concat((posts, dists_df), axis=1)
posts.drop(["text"], axis=1, inplace=True)
posts

,post_id,topic,TextCluster,DistanceToCluster_0,DistanceToCluster_1,DistanceToCluster_2,DistanceToCluster_3,DistanceToCluster_4,DistanceToCluster_5,DistanceToCluster_6,DistanceToCluster_7,DistanceToCluster_8,DistanceToCluster_9
0,1,business,9,3.375463,2.827366,3.286124,3.392758,3.609495,3.388122,2.366426,2.194448,2.990085,1.770638
1,2,business,9,3.329094,2.551211,2.962308,3.332920,3.347059,3.150867,2.333067,2.211535,2.838212,1.707563
2,3,business,9,3.264548,2.863519,3.058967,3.384545,3.348653,3.204419,2.392042,3.004334,3.041477,1.611540
3,4,business,9,3.521580,3.357555,3.793170,3.658642,3.795354,3.722914,2.815526,3.367651,3.250493,2.338428
4,5,business,9,3.049469,2.134254,2.847575,2.814365,3.043573,2.751275,2.034956,2.911702,2.653575,1.706435
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7018,7315,movie,3,3.134072,2.289354,3.086797,1.441693,2.937230,1.764968,2.726515,3.334631,2.815605,2.929035
7019,7316,movie,3,2.932566,2.189001,3.131474,1.029670,2.584817,1.689919,2.436663,3.171558,2.506205,2.925116
7020,7317,movie,3,2.831795,2.407472,3.170171,1.677144,2.368957,1.947715,2.801324,3.386631,2.531627,3.157414
7021,7318,movie,3,3.432252,2.253021,3.155417,1.290190,3.292484,1.371549,2.973925,3.426645,3.102832,3.175596
7022,7319,movie,5,3.297546,2.628579,3.301529,2.067861,3.025123,1.806361,2.892133,3.548831,2.975862,3.210715

In [15]:
# Очищаем память

model.cpu()

del model
del tokenizer
del dataset
del loader
del embeddings
del centered
del pca
del pca_decomp

import gc
gc.collect()

51

In [18]:
# Сохраняем в базу фичи, необходимые для функционала модели

posts.to_sql(
   "vl_aleksandrov_posts_info_features_dl",
    con=engine,
    schema="public",
    if_exists='replace'
)

23

## Обработка действий

In [20]:
# Берем 7 миллионов и оставляем только action = view


feed_data = pd.read_sql(
    """
    SELECT
        cast(extract(hour from timestamp) as int) as hour,
        cast(extract(month from timestamp) as int) as month,
        post_id,
        gender,
        age,
        country,
        city,
        exp_group,
        os,
        source,
        target
    FROM public.feed_data JOIN public.user_data ON public.feed_data.user_id = public.user_data.user_id
    WHERE action = 'view'
    LIMIT 7000000
    """,
    con=engine
)

feed_data.head()

,hour,month,post_id,gender,age,country,city,exp_group,os,source,target
0,22,11,4487,1,34,Russia,Moscow,0,iOS,ads,0
1,22,11,4719,1,34,Russia,Moscow,0,iOS,ads,1
2,22,11,6875,1,34,Russia,Moscow,0,iOS,ads,0
3,22,11,5649,1,34,Russia,Moscow,0,iOS,ads,0
4,22,11,3689,1,34,Russia,Moscow,0,iOS,ads,0

In [21]:
# Обучим катбуст

from catboost import CatBoostClassifier

object_cols = [
    'topic', 'TextCluster', 'gender', 'country',
    'city', 'exp_group', 'hour', 'month',
    'os', 'source'
]

catboost = CatBoostClassifier(
    iterations=100,
    learning_rate=1,
    depth=2,
    thread_count=-1,
    task_type="GPU"
)

feed_data = pd.merge(
    feed_data,
    posts,
    on='post_id',
    how='left'
)

feed_data.drop(['post_id'], axis=1, inplace=True)

catboost.fit(X=feed_data.drop(['target'], axis=1), y=feed_data['target'], cat_features=object_cols)

0:	learn: 0.3641878	total: 199ms	remaining: 19.7s
1:	learn: 0.3561099	total: 270ms	remaining: 13.2s
2:	learn: 0.3546930	total: 340ms	remaining: 11s
3:	learn: 0.3541964	total: 407ms	remaining: 9.77s
4:	learn: 0.3538420	total: 467ms	remaining: 8.88s
5:	learn: 0.3536517	total: 529ms	remaining: 8.28s
6:	learn: 0.3533452	total: 585ms	remaining: 7.78s
7:	learn: 0.3529825	total: 642ms	remaining: 7.39s
8:	learn: 0.3528819	total: 702ms	remaining: 7.09s
9:	learn: 0.3515555	total: 759ms	remaining: 6.83s
10:	learn: 0.3514356	total: 817ms	remaining: 6.61s
11:	learn: 0.3513859	total: 874ms	remaining: 6.41s
12:	learn: 0.3513417	total: 931ms	remaining: 6.23s
13:	learn: 0.3513129	total: 988ms	remaining: 6.07s
14:	learn: 0.3511723	total: 1.04s	remaining: 5.92s
15:	learn: 0.3505977	total: 1.1s	remaining: 5.8s
16:	learn: 0.3505476	total: 1.16s	remaining: 5.67s
17:	learn: 0.3505213	total: 1.22s	remaining: 5.56s
18:	learn: 0.3500243	total: 1.28s	remaining: 5.45s
19:	learn: 0.3497760	total: 1.33s	remaining: 5.34s
20:	learn: 0.3495783	total: 1.39s	remaining: 5.24s
21:	learn: 0.3495474	total: 1.45s	remaining: 5.14s
22:	learn: 0.3494831	total: 1.51s	remaining: 5.05s
23:	learn: 0.3492880	total: 1.57s	remaining: 4.96s
24:	learn: 0.3488209	total: 1.63s	remaining: 4.88s
25:	learn: 0.3487379	total: 1.68s	remaining: 4.79s
26:	learn: 0.3485373	total: 1.74s	remaining: 4.71s
27:	learn: 0.3484133	total: 1.8s	remaining: 4.63s
28:	learn: 0.3483606	total: 1.86s	remaining: 4.54s
29:	learn: 0.3483267	total: 1.92s	remaining: 4.47s
30:	learn: 0.3482382	total: 1.97s	remaining: 4.39s
31:	learn: 0.3482159	total: 2.03s	remaining: 4.32s
32:	learn: 0.3481806	total: 2.09s	remaining: 4.24s
33:	learn: 0.3481738	total: 2.15s	remaining: 4.17s
34:	learn: 0.3481485	total: 2.2s	remaining: 4.09s
35:	learn: 0.3481287	total: 2.26s	remaining: 4.02s
36:	learn: 0.3481083	total: 2.32s	remaining: 3.95s
37:	learn: 0.3481047	total: 2.38s	remaining: 3.88s
38:	learn: 0.3480611	total: 2.44s	remaining: 3.81s
39:	learn: 0.3480194	total: 2.49s	remaining: 3.74s
40:	learn: 0.3480111	total: 2.55s	remaining: 3.67s
41:	learn: 0.3479956	total: 2.61s	remaining: 3.61s
42:	learn: 0.3479806	total: 2.67s	remaining: 3.54s
43:	learn: 0.3479753	total: 2.73s	remaining: 3.47s
44:	learn: 0.3479669	total: 2.79s	remaining: 3.4s
45:	learn: 0.3478169	total: 2.84s	remaining: 3.34s
46:	learn: 0.3477800	total: 2.9s	remaining: 3.27s
47:	learn: 0.3477056	total: 2.96s	remaining: 3.21s
48:	learn: 0.3476715	total: 3.02s	remaining: 3.14s
49:	learn: 0.3475849	total: 3.08s	remaining: 3.08s
50:	learn: 0.3475792	total: 3.14s	remaining: 3.01s
51:	learn: 0.3475088	total: 3.2s	remaining: 2.95s
52:	learn: 0.3474850	total: 3.25s	remaining: 2.89s
53:	learn: 0.3474533	total: 3.31s	remaining: 2.82s
54:	learn: 0.3474387	total: 3.37s	remaining: 2.76s
55:	learn: 0.3474332	total: 3.43s	remaining: 2.69s
56:	learn: 0.3473986	total: 3.49s	remaining: 2.63s
57:	learn: 0.3473877	total: 3.54s	remaining: 2.57s
58:	learn: 0.3473700	total: 3.6s	remaining: 2.5s
59:	learn: 0.3473178	total: 3.66s	remaining: 2.44s
60:	learn: 0.3473007	total: 3.72s	remaining: 2.38s
61:	learn: 0.3472711	total: 3.78s	remaining: 2.31s
62:	learn: 0.3472588	total: 3.84s	remaining: 2.25s
63:	learn: 0.3472366	total: 3.89s	remaining: 2.19s
64:	learn: 0.3472240	total: 3.95s	remaining: 2.13s
65:	learn: 0.3472135	total: 4.01s	remaining: 2.06s
66:	learn: 0.3472054	total: 4.07s	remaining: 2s
67:	learn: 0.3471724	total: 4.13s	remaining: 1.94s
68:	learn: 0.3471682	total: 4.18s	remaining: 1.88s
69:	learn: 0.3471638	total: 4.24s	remaining: 1.82s
70:	learn: 0.3471466	total: 4.3s	remaining: 1.76s
71:	learn: 0.3471391	total: 4.36s	remaining: 1.7s
72:	learn: 0.3471216	total: 4.42s	remaining: 1.63s
73:	learn: 0.3471126	total: 4.47s	remaining: 1.57s
74:	learn: 0.3470782	total: 4.53s	remaining: 1.51s
75:	learn: 0.3470589	total: 4.59s	remaining: 1.45s
76:	learn: 0.3470531	total: 4.65s	remaining: 1.39s
77:	learn: 0.3470273	total: 4.71s	remaining: 1.33s
78:	learn: 0.3470187	total: 4.76s	remaining: 1.27s
79:	learn: 0.3470157	total: 4.82s	remaining: 1.21s
80:	learn: 0.3470088	total: 4.88s	remaining: 1.15s
81:	learn: 0.3469847	total: 4.94s	remaining: 1.08s
82:	learn: 0.3468952	total: 5s	remaining: 1.02s
83:	learn: 0.3468614	total: 5.05s	remaining: 963ms
84:	learn: 0.3468482	total: 5.11s	remaining: 902ms
85:	learn: 0.3468379	total: 5.17s	remaining: 842ms
86:	learn: 0.3468031	total: 5.23s	remaining: 781ms
87:	learn: 0.3467789	total: 5.29s	remaining: 721ms
88:	learn: 0.3467660	total: 5.35s	remaining: 661ms
89:	learn: 0.3467478	total: 5.4s	remaining: 600ms
90:	learn: 0.3467390	total: 5.46s	remaining: 540ms
91:	learn: 0.3467309	total: 5.52s	remaining: 480ms
92:	learn: 0.3467245	total: 5.58s	remaining: 420ms
93:	learn: 0.3467032	total: 5.64s	remaining: 360ms
94:	learn: 0.3466840	total: 5.69s	remaining: 300ms
95:	learn: 0.3466793	total: 5.75s	remaining: 240ms
96:	learn: 0.3466746	total: 5.81s	remaining: 180ms
97:	learn: 0.3466258	total: 5.87s	remaining: 120ms
98:	learn: 0.3466198	total: 5.93s	remaining: 59.9ms
99:	learn: 0.3466064	total: 5.98s	remaining: 0us

In [23]:
# Сохраняем модель

catboost.save_model(
    'catboost_model.cbm',
    format="cbm"                  
)